[odoo-main]
description = "Backup main odoo db"
conninfo = host={{ main_srv }} user=barman_odoo dbname=beamz
streaming_conninfo = host={{ main_srv }} user=barman_odoo
backup_method = postgres
streaming_archiver = on
slot_name = barman
create_slot = auto
# backup_method = rsync
# ssh_command = ssh postgres@pg
# reuse_backup = link