; Barman, Backup and Recovery Manager for PostgreSQL
; http://www.pgbarman.org/ - http://www.enterprisedb.com/
;
; Main configuration file

[barman]
; System user
barman_user = barman
configuration_files_directory = /etc/barman.d
barman_home = /home/barman
log_file = /var/log/barman/barman.log
log_level = INFO
compression = gzip
last_backup_maximum_age = 2 DAYS
minimum_redundancy = 80
retention_policy = RECOVERY WINDOW OF 12 WEEKS
